### PR TITLE
2.1.0

### PR DESCRIPTION
**Pull request by j0k3r**
I think we can release 2.1.0 now with Signing Key supports.

What do you think @zeeshanu?

### CODE REVIEW

**Comment by zeeshanu** [comment]
@j0k3r If you want to make a release yourself you have to create phar file using box package or i would create it myself and make a release. 😃

**Comment by j0k3r** [comment]
Maybe you can create a `RELEASE.md` file at the root level with all steps to generate a new release :slightly_smiling_face: It might help if you get more collaborators and I'll then know how to publish a new release

**Comment by zeeshanu** [comment]
Ok thanks i will

**Comment by zeeshanu** [comment]
@j0k3r [done](https://github.com/zeeshanu/git-profile/blob/master/RELEASE.md) :+1:

**Comment by j0k3r** [comment]
Great !

**Pull request merged**
