### PR TITLE
More tests

### PR DESCRIPTION
**Pull request by j0k3r**
~~**:warning: https://github.com/zeeshanu/git-profile/pull/11 needs to be merged first then I'll rebase this PR to remove extra commits from the previous PR**~~

This PR adds more tests.

I converted `exit()` code to Exception to be able to test commands.
Results are the same.

Coverage is far better :green_heart: 

image

### CODE REVIEW

**Comment by zeeshanu** [comment]
@j0k3r thank you for putting your time. Plus I made you a collaborator so that you can push directly, if you are interested :)

**Comment by j0k3r** [comment]
Oh yeah just saw that, thanks :+1:

**Comment by j0k3r** [comment]
Could you add me as a maintainer [here](https://packagist.org/packages/zeeshanu/git-profile/maintainers/)?

**Comment by zeeshanu** [comment]
@j0k3r Done

**Pull request merged**
